export const SET_IS_LOGIN = "SET_IS_LOGIN";
export const SET_ERROR = "SET_ERROR"
export const SET_ALL_TRANSACTION_USER = "SET_ALL_TRANSACTION_USER";
export const SET_TRANSACTION_BY_DATE = "SET_TRANSACTION_BY_DATE";
export const SET_TRANSACTION_BY_CATEGORY = "SET_TRANSACTION_BY_CATEGORY";
export const SET_LOADING_TRANSACTION = "SET_LOADING_TRANSACTION";
export const SET_ERROR_LOGIN = 'SET_ERROR_LOGIN'
